services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - games
      - docs
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  games:
    build:
      context: .
      dockerfile: Dockerfile.games
    command: ["npx", "http-server", "-p", "4000", "games/docs"]
    ports:
      - "4000:4000"
    tty: true

  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    command: ["npx", "http-server", "-p", "4001", "docs"]
    ports:
      - "4001:4001"
    tty: true

volumes:
  node_modules: {}
