version: '3'

services:
  app:
    build:
      context: .
    tty: true
    environment:
      API_BASE_URL: "http://localhost:3000/api"
    ports:
      - 3000:3000
    volumes:
      - ./src:/app
    command: sh -c "npm run dev"
