services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - wasmgames
      - markdown
    env_file:
      - .env.local
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true

  wasmgames:
    build:
      context: .
      dockerfile: Dockerfile.wasmgames
    command: ["npx", "http-server", "-p", "4000", "wasm-games"]
    ports:
      - "4000:4000"
    tty: true

  markdown:
    build:
      context: .
      dockerfile: Dockerfile.markdowns
    command: ["npx", "http-server", "-p", "4001", "markdown"]
    ports:
      - "4001:4001"
    tty: true

volumes:
  node_modules: {}
